[build.environment]
# Cache Cypress binary in local `node_modules` folder, so Netlify caches it.
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# Set variable for terminal output.
TERM = "xterm"
[[plugins]]
  # Execute Cypress end-to-end tests against the deployed URL.
  package = "netlify-plugin-cypress"
    [plugins.inputs]
    record = true
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
